#!/bin/bash
APPLICATION_HOME="$( cd "$( dirname "$0" )" && pwd )"
cd "$APPLICATION_HOME"

JAVA_COMMAND="$APPLICATION_HOME/jre/bin/java"
JVM_ARGS="-Xmx64M -XX:+CMSClassUnloadingEnabled -jar"

exec "$JAVA_COMMAND" $JVM_ARGS "Leikr-0.0.9.jar" 
